# Generated by Django 4.2.4 on 2023-11-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=40)),
                ('disponible', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
